  query User($id: ID!) {
    user(id: $id) {
      id
      username
      languages {
        name
        icon
        id
      }
      infos {
        avatar
        created_at
        description
        role
      }
      email
    }
  }
